Repository isomerpages/pa-cdcvouchers, pull requests merged in 2021-12, with the labels that each got.

#3 Fixed the auto-numbering issues on guide pages
  _merchants/Merchants' Guide/Bagaimana untuk menggunakan RedeemSG Merchant.md
  _merchants/Merchants' Guide/Onboard RedeemSG Merchant App.md
  _merchants/Merchants' Guide/RedeemSG Merchant செயலியில் பதிவு செய்யுங்கள்.md
  _merchants/Merchants' Guide/加入 RedeemSG Merchant 手机应用程序.md
Labels: bug

#5 Content, Images, Housekeeping
  Resources/guides-for-residents/_posts/2021-12-13-file-Step by Step Guide for Residents in Chinese.md
  Resources/guides-for-residents/_posts/2021-12-13-file-Step by Step Guide for Residents in English.md
  Resources/guides-for-residents/_posts/2021-12-13-file-Step by Step Guide for Residents in Malay.md
  Resources/guides-for-residents/_posts/2021-12-13-file-Step by Step Guide for Residents in Tamil.md
  _about/Terms & Conditions.md
  _merchants/Merchants' FAQ.md
  _residents/Residents' FAQ.md
  _residents/Residents' Guide/CDC பற்றுச்சீட்டுகளைப் பெற்றுக் கொள்ளுங்கள்.md
  _residents/Residents' Guide/How to Claim & Use CDC Vouchers.md
  images/residents/screengrabs-for-infographics/english/Masked NRIC.jpg
  pages/Contact Us.md
Labels: bug, enhancement

#6 FAQ fixes
  _config.yml
  _merchants/Merchants' FAQ.md
  _residents/Residents' FAQ.md
  _residents/Residents' Guide/CDC பற்றுச்சீட்டுகளைப் பெற்றுக் கொள்ளுங்கள்.md
  images/merchants/m-bank-supporting-doc-bankprofile.png
  images/merchants/m-bank-supporting-doc-bankstatement.png
  images/merchants/m-sample-digital-ambassador-badge-wo-text.png
  images/merchants/m-sample-digital-ambassador-lanyard2.png
  images/merchants/m-sample-digital-ambassador-uniform-wo-text.png
  images/residents/Redeemed.png
  images/residents/ScanQR Reveal.png
Labels: bug

#7 UI Fix
  _residents/Residents' Guide/CDC பற்றுச்சீட்டுகளைப் பெற்றுக் கொள்ளுங்கள்.md
Labels: good first issue

#8 Corrected image
  _residents/Residents' FAQ.md
  images/residents/FAQ 5b.jpg
  images/residents/faq5b2.png
  images/residents/redeem_sms.jpg
Labels: good first issue

#9 Insert CDC VOUCHER DECAL
  _residents/Residents' FAQ.md
Labels: enhancement

#10 Added pull request
  _residents/Get Started.md
  files/Authorisation Form.pdf
Labels: enhancement

#11 Update file: Get Started.md
  _residents/Get Started.md
Labels: enhancement

#13 Update file: Residents' FAQ.md
  _residents/Residents' FAQ.md
Labels: enhancement
